### ISSUE TITLE
Feature Request: parse SPN IDs for JSON as well

### ISSUE THREAD

**Issue by cjkoenig** [Polyconseil/libcanardbc#6]
I would love to have the SPN ID in the signals section of a json file. The ID of an SPN can be found in this line of a dbc file:

`BA_ "SPN" SG_ <message_id> <signal name> <signal ID>;`

With some hints, I might be able to implement it on my own (and send a PR, for sure).

**Comment by rsebille** [comment]
Hello,

The good news is the parser seems to already knows those tokens :).
https://github.com/Polyconseil/libcanardbc/blob/aeb7ed3ded5b593f412c1ca6420068017d6e5c30/src/candbc-parser.y#L557-L575

The next step would be to export those signals attributes in this loop:
https://github.com/Polyconseil/libcanardbc/blob/aeb7ed3ded5b593f412c1ca6420068017d6e5c30/tools/dbc2json.c#L28

And you can probably reuse this function:
https://github.com/Polyconseil/libcanardbc/blob/aeb7ed3ded5b593f412c1ca6420068017d6e5c30/tools/dbc2json.c#L184

Message's attributes are already exported so I think it is a good place to look at if you want to export signal's attributes.

**Comment by cjkoenig** [comment]
Thank you for the hints- I made it and will submit a PR (hopefully) this evening.
