### ISSUE TITLE
Please Tell me How to install in Windows

### ISSUE THREAD

**Issue by kamarajanis** [Polyconseil/libcanardbc#8]
And also how to run it
whether in cmd or anywhere else 
Because i don't how to do it

**Comment by vperron** [comment]
We are not a customer support team. Figure it out and update the docs.

**Comment by vperron** [comment]
I realize my message was a little too harsh.

The way open source works is not by requesting that the current contributors do something for you for free on their free time; it's way more about trying to contribute in various ways by getting into the code, its documentation, identifying the eventual issues and proposing improvements in the form of constructive comments or a pull request.

What I mean is, we probably never had the time to try and write the documentation for Windows; but you could be the first to help us do it and make the software better in the process !

All the best,

**Comment by kamarajanis** [comment]
Sorry I don't  know that's  why asked if anyone knows or author please update the docs
